<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DashboardWidget;

class DashboardWidgetSeeder extends Seeder
{
    public function run(): void
    {
        $widgets = [
            // Admin Widgets
            [
                'name' => 'Total Students',
                'widget_key' => 'total_students',
                'widget_type' => 'stat',
                'icon' => 'users',
                'color' => 'primary',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getKeyMetrics',
                'configuration' => ['metric' => 'total_students'],
                'is_active' => true,
                'sort_order' => 1,
                'refresh_interval' => 300,
            ],
            [
                'name' => 'Total Teachers',
                'widget_key' => 'total_teachers',
                'widget_type' => 'stat',
                'icon' => 'user-tie',
                'color' => 'success',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getKeyMetrics',
                'configuration' => ['metric' => 'total_teachers'],
                'is_active' => true,
                'sort_order' => 2,
                'refresh_interval' => 300,
            ],
            [
                'name' => 'Monthly Revenue',
                'widget_key' => 'total_revenue',
                'widget_type' => 'stat',
                'icon' => 'dollar-sign',
                'color' => 'warning',
                'roles' => ['Super Admin', 'Admin', 'Accountant'],
                'data_source' => 'getKeyMetrics',
                'configuration' => ['metric' => 'total_revenue'],
                'is_active' => true,
                'sort_order' => 3,
                'refresh_interval' => 300,
            ],
            [
                'name' => 'Pending Fees',
                'widget_key' => 'pending_fees',
                'widget_type' => 'stat',
                'icon' => 'alert-circle',
                'color' => 'danger',
                'roles' => ['Super Admin', 'Admin', 'Accountant'],
                'data_source' => 'getKeyMetrics',
                'configuration' => ['metric' => 'pending_fees'],
                'is_active' => true,
                'sort_order' => 4,
                'refresh_interval' => 300,
            ],
            [
                'name' => 'Student Enrollment Trend',
                'widget_key' => 'enrollment_chart',
                'widget_type' => 'chart',
                'chart_type' => 'line',
                'icon' => 'trending-up',
                'color' => 'primary',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getStudentEnrollmentTrend',
                'configuration' => ['height' => 300],
                'is_active' => true,
                'sort_order' => 5,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Attendance Trend',
                'widget_key' => 'attendance_chart',
                'widget_type' => 'chart',
                'chart_type' => 'bar',
                'icon' => 'calendar-check',
                'color' => 'success',
                'roles' => ['Super Admin', 'Admin', 'Teacher'],
                'data_source' => 'getAttendanceTrend',
                'configuration' => ['height' => 300, 'days' => 30],
                'is_active' => true,
                'sort_order' => 6,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Fee Collection',
                'widget_key' => 'fee_collection_chart',
                'widget_type' => 'chart',
                'chart_type' => 'bar',
                'icon' => 'bar-chart',
                'color' => 'warning',
                'roles' => ['Super Admin', 'Admin', 'Accountant'],
                'data_source' => 'getMonthlyFeeCollection',
                'configuration' => ['height' => 300],
                'is_active' => true,
                'sort_order' => 7,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Income vs Expense',
                'widget_key' => 'income_expense_chart',
                'widget_type' => 'chart',
                'chart_type' => 'line',
                'icon' => 'trending-up',
                'color' => 'info',
                'roles' => ['Super Admin', 'Admin', 'Accountant'],
                'data_source' => 'getIncomeVsExpense',
                'configuration' => ['height' => 300, 'months' => 6],
                'is_active' => true,
                'sort_order' => 8,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Class Distribution',
                'widget_key' => 'class_distribution_chart',
                'widget_type' => 'chart',
                'chart_type' => 'pie',
                'icon' => 'pie-chart',
                'color' => 'purple',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getClassDistribution',
                'configuration' => ['height' => 300],
                'is_active' => true,
                'sort_order' => 9,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Gender Distribution',
                'widget_key' => 'gender_distribution_chart',
                'widget_type' => 'chart',
                'chart_type' => 'doughnut',
                'icon' => 'pie-chart',
                'color' => 'pink',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getGenderDistribution',
                'configuration' => ['height' => 300],
                'is_active' => true,
                'sort_order' => 10,
                'refresh_interval' => 600,
            ],
            [
                'name' => "Today's Attendance",
                'widget_key' => 'today_attendance',
                'widget_type' => 'list',
                'icon' => 'check-circle',
                'color' => 'success',
                'roles' => ['Super Admin', 'Admin', 'Teacher'],
                'data_source' => 'getTodayAttendance',
                'configuration' => [],
                'is_active' => true,
                'sort_order' => 11,
                'refresh_interval' => 300,
            ],
            [
                'name' => 'Upcoming Exams',
                'widget_key' => 'upcoming_exams',
                'widget_type' => 'list',
                'icon' => 'book-open',
                'color' => 'primary',
                'roles' => ['Super Admin', 'Admin', 'Teacher', 'Student'],
                'data_source' => 'getUpcomingExams',
                'configuration' => ['limit' => 5],
                'is_active' => true,
                'sort_order' => 12,
                'refresh_interval' => 3600,
            ],
            [
                'name' => 'Upcoming Events',
                'widget_key' => 'upcoming_events',
                'widget_type' => 'list',
                'icon' => 'calendar',
                'color' => 'info',
                'roles' => ['Super Admin', 'Admin', 'Teacher', 'Student', 'Parent'],
                'data_source' => 'getUpcomingEvents',
                'configuration' => ['limit' => 5],
                'is_active' => true,
                'sort_order' => 13,
                'refresh_interval' => 3600,
            ],
            [
                'name' => 'Recent Activities',
                'widget_key' => 'recent_activities',
                'widget_type' => 'list',
                'icon' => 'activity',
                'color' => 'secondary',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getRecentActivities',
                'configuration' => ['limit' => 10],
                'is_active' => true,
                'sort_order' => 14,
                'refresh_interval' => 300,
            ],
            // Teacher Specific Widgets
            [
                'name' => 'My Classes',
                'widget_key' => 'teacher_classes',
                'widget_type' => 'list',
                'icon' => 'users',
                'color' => 'primary',
                'roles' => ['Teacher'],
                'data_source' => 'getTeacherClasses',
                'configuration' => [],
                'is_active' => true,
                'sort_order' => 1,
                'refresh_interval' => 600,
            ],
            [
                'name' => "Today's Schedule",
                'widget_key' => 'today_schedule',
                'widget_type' => 'table',
                'icon' => 'calendar',
                'color' => 'info',
                'roles' => ['Teacher'],
                'data_source' => 'getTeacherTodayClasses',
                'configuration' => [],
                'is_active' => true,
                'sort_order' => 2,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Teacher Workload',
                'widget_key' => 'teacher_workload_chart',
                'widget_type' => 'chart',
                'chart_type' => 'bar',
                'icon' => 'bar-chart',
                'color' => 'warning',
                'roles' => ['Super Admin', 'Admin'],
                'data_source' => 'getTeacherWorkload',
                'configuration' => ['height' => 300],
                'is_active' => true,
                'sort_order' => 15,
                'refresh_interval' => 600,
            ],
            // Student Specific Widgets
            [
                'name' => 'My Attendance',
                'widget_key' => 'student_attendance',
                'widget_type' => 'stat',
                'icon' => 'calendar-check',
                'color' => 'success',
                'roles' => ['Student', 'Parent'],
                'data_source' => 'getStudentAttendance',
                'configuration' => [],
                'is_active' => true,
                'sort_order' => 1,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'My Fee Status',
                'widget_key' => 'student_fee_status',
                'widget_type' => 'stat',
                'icon' => 'dollar-sign',
                'color' => 'warning',
                'roles' => ['Student', 'Parent'],
                'data_source' => 'getStudentFeeStatus',
                'configuration' => [],
                'is_active' => true,
                'sort_order' => 2,
                'refresh_interval' => 600,
            ],
            [
                'name' => 'Recent Results',
                'widget_key' => 'student_results',
                'widget_type' => 'table',
                'icon' => 'award',
                'color' => 'primary',
                'roles' => ['Student', 'Parent'],
                'data_source' => 'getStudentRecentResults',
                'configuration' => ['limit' => 10],
                'is_active' => true,
                'sort_order' => 3,
                'refresh_interval' => 600,
            ],
            // Librarian Widgets
            [
                'name' => 'Library Circulation',
                'widget_key' => 'library_circulation_chart',
                'widget_type' => 'chart',
                'chart_type' => 'line',
                'icon' => 'book',
                'color' => 'orange',
                'roles' => ['Super Admin', 'Admin', 'Librarian'],
                'data_source' => 'getLibraryCirculation',
                'configuration' => ['height' => 300, 'months' => 6],
                'is_active' => true,
                'sort_order' => 1,
                'refresh_interval' => 600,
            ],
        ];

        foreach ($widgets as $widget) {
            DashboardWidget::create($widget);
        }
    }
}
